version: '3.7'

services:
  api:
    build:
        context: .
        dockerfile: dev.Dockerfile
    volumes:
      - ./:/usr/api/
      - /usr/api/node_modules
    ports:
      - 3000:3000
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://root:password@postgres/db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: localhost
      POSTGRES_DB: db
      PORT: 3000
      NODE_ENV: development
      MAILCHIMP_API: 
      MAILCHIMP_AUDIENCE: 
      MAILJET_API_KEY: xxxx
      MAILJET_API_SECRET:
      MANDRILL_API:
      JWT_SECRET: base64secret
    networks:
      - packstack

  postgres:
    restart: always
    image: postgres:11.3-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - packstack

networks:
  packstack:

volumes:
  pgdata:
